
steps:

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f','docker-compose.cloudbuild.yaml','up','-d'] #-f : informar qual o arquivo, e nome do arquivo 
# arquivo para o GCP executar as tarefas passo a passo